export default function Head() {
  return (
    <>
      <title>여기에 매력적 문구,-홈페이지 제목</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  )
}
